// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6UuPaM1SR8deqsbZWfj3EYGXJuIEjIno',
    appId: '1:745162008445:web:0eb73bcdbf7c8755b94e14',
    messagingSenderId: '745162008445',
    projectId: 'school-sync-cd946',
    authDomain: 'school-sync-cd946.firebaseapp.com',
    storageBucket: 'school-sync-cd946.firebasestorage.app',
    measurementId: 'G-SPXCDLZK9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbTFwnnPSY3-8VuDjheb19VsP6a1Ddacw',
    appId: '1:745162008445:android:ae14f0cf5dce6b4fb94e14',
    messagingSenderId: '745162008445',
    projectId: 'school-sync-cd946',
    storageBucket: 'school-sync-cd946.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-3hbKhzcIISkRUxT7L9QN9VQGWc0B9g',
    appId: '1:745162008445:ios:48eb284af948c799b94e14',
    messagingSenderId: '745162008445',
    projectId: 'school-sync-cd946',
    storageBucket: 'school-sync-cd946.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-3hbKhzcIISkRUxT7L9QN9VQGWc0B9g',
    appId: '1:745162008445:ios:48eb284af948c799b94e14',
    messagingSenderId: '745162008445',
    projectId: 'school-sync-cd946',
    storageBucket: 'school-sync-cd946.firebasestorage.app',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6UuPaM1SR8deqsbZWfj3EYGXJuIEjIno',
    appId: '1:745162008445:web:bf60f82fdc9442dfb94e14',
    messagingSenderId: '745162008445',
    projectId: 'school-sync-cd946',
    authDomain: 'school-sync-cd946.firebaseapp.com',
    storageBucket: 'school-sync-cd946.firebasestorage.app',
    measurementId: 'G-7GDJCCS6Z9',
  );
}
